name: cinar-soe
channels:
  - conda-forge
  - defaults
dependencies:
  - netcdf4==1.7.1
  - numpy==2.1.1
  - matplotlib==3.9.2
  - pandas==2.2.3
  - xarray==2024.9.0
  - cartopy==0.23.0
  - cmocean==4.0.3
  - cool_maps==1.0.1
  - pyco2sys==1.8.3.3
  - erddapy==2.2.4
