acknowledgment: Funding provided by the National Oceanic and Atmospheric Administration
contributor_name: Grace Saba,Lori Garzio
contributor_role: Principal Investigator,Data Management
creator_institution: Rutgers University
creator_email: lgarzio@marine.rutgers.edu
creator_name: Lori Garzio
creator_url: rucool.marine.rutgers.edu
comment: Synthesis of surface and bottom pH and aragonite saturation state data from vessel-based and glider-based measurements that were spatially limited to the U.S. Northeast Shelf.
institution: Rutgers University
program: NOAA Ocean Acidification Program
project: xxxx
title: vessel_glider_surface_bottom_OA_data_NES
history: xx
Conventions: CF-1.11
