global_attrs:
  acknowledgment: Funding provided by the National Oceanic and Atmospheric Administration
  contributor_name: Grace Saba,Lori Garzio
  contributor_role: Principal Investigator,Data Management
  creator_institution: Rutgers University
  creator_email: lgarzio@marine.rutgers.edu
  creator_name: Lori Garzio
  creator_url: rucool.marine.rutgers.edu
  comment: Synthesis of surface and bottom pH and aragonite saturation state data from vessel-based and glider-based measurements that were spatially limited to the U.S. Northeast Shelf.
  institution: Rutgers University
  program: NOAA Ocean Acidification Program
  project: xxxx
  title: Surface and bottom OA data along the US Northeast Shelf
  history: xx
  conventions: CF-1.11
  infoUrl: https://rucool.marine.rutgers.edu/
variable_attrs:
  collection_method:
    units: '1'
    long_name: Collection method
    comment: Glider or vessel-based data
  station_water_depth:
    units: m
    long_name: Bottom Depth
    description: Depth of water column at the sampling station
    comment: For vessel datasets, from the original data source, when provided. When not provided, bottom
      depth was calculated using the sample coordinates and GEBCO’s gridded global
      bathymetry (https://download.gebco.net/). For glider datasets, bottom depth was calculated using the 
      sample coordinates and GEBCO’s gridded global bathymetry.
  pH_surface:
    units: '1'
    long_name: Surface pH
    comment: For the CODAP-NA v2021 dataset (vessel-based), pH_TS_insitu_measured was used when
      available. Otherwise, pH_TS_insitu_calculated was used. For the additional vessel-based datasets downloaded
      from NCEI, pH at in situ temperature, pressure, and salinity were calculated
      from pH_TS_20C using PyCO2SYS. For glider datasets, the pH provided in each dataset was used.
    description: For vessel datasets, surface pH is the shallowest measurement of a vertical CTD/Rosette
      cast if the sample depth was < 10m. For stations with multiple samples at
      the shallowest depth, the median value was calculated. For glider datasets, 
      surface pH is the the median of the values recorded at the top of a glider profile 
      (between 2-4m depth), provided the glider profile reached at least 10m depth.
  pH_bottom:
    units: '1'
    long_name: Bottom pH
    comment: For the CODAP-NA v2021 dataset (vessel-based), pH_TS_insitu_measured was used when
      available. Otherwise, pH_TS_insitu_calculated was used. For the additional vessel-based datasets downloaded
      from NCEI, pH at in situ temperature, pressure, and salinity were calculated
      from pH_TS_20C using PyCO2SYS. For glider datasets, the pH provided in each dataset was used.
    description: For vessel datasets, bottom pH is the deepest measurement of a vertical CTD/Rosette
      cast where water samples were collected for profiles deeper than 10m, provided
      the sampling depth was no shallower than the bottom 20% of total water column
      depth. For stations with multiple samples at the deepest measurement, the
      median value was calculated. For glider datasets, bottom pH is the the median of the values within the 
      deepest 1m of a glider profile, provided the sampling depth was no shallower than the bottom 20% of total 
      water column depth.
  omega_surface:
    units: '1'
    long_name: Surface Aragonite Saturation State
    comment: From the original data source, when available. When not available, 
      calculated using PyCO2SYS (Humphreys et al.
      2020) with inputs of pressure, temperature, salinity, total alkalinity, and
      pH.
    description: For vessel datasets, surface aragonite saturation state is the shallowest measurement
      of a vertical CTD/Rosette cast if the sample depth was < 10m. For stations
      with multiple samples at the shallowest depth, the median value was calculated. For glider datasets, 
      surface aragonite saturation state is the the median of the values recorded at the 
      top of a glider profile (between 2-4m depth), provided the glider profile reached at least 10m depth.
  omega_bottom:
    units: '1'
    long_name: Bottom Aragonite Saturation State
    comment: From the original data source, when
      available. When not available, calculated using PyCO2SYS (Humphreys et al.
      2020) with inputs of pressure, temperature, salinity, total alkalinity, and
      pH.
    description: For vessel datasets, bottom aragonite saturation state is the deepest measurement of
      a vertical CTD/Rosette cast where water samples were collected for profiles
      deeper than 10m, provided the sampling depth was no shallower than the bottom
      20% of total water column depth. For stations with multiple samples at the
      deepest measurement, the median value was calculated. For glider datasets, bottom aragonite saturation 
      state is the the median of the values within the deepest 
      1m of a glider profile, provided the sampling depth was no shallower than the bottom 
      20% of total water column depth.
  temperature_surface:
    units: C
    long_name: Surface Temperature
    description: For vessel datasets, surface seawater temperature is the shallowest measurement of a
      vertical CTD/Rosette cast if the sample depth was < 10m. For stations with
      multiple samples at the shallowest depth, the median value was calculated. For glider datasets,
      surface temperature is the the median of the values recorded at the 
      top of a glider profile (between 2-4m depth), provided the glider profile reached at least 10m depth.
  temperature_bottom:
    units: C
    long_name: Bottom Temperature
    description: For vessel datasets, bottom seawater temperature is the deepest measurement of a vertical
      CTD/Rosette cast where water samples were collected for profiles deeper than
      10m, provided the sampling depth was no shallower than the bottom 20% of total
      water column depth. For stations with multiple samples at the deepest measurement,
      the median value was calculated. For glider datasets, Bottom temperature is the the median 
      of the values within the deepest 1m of a glider profile, provided the sampling depth was no 
      shallower than the bottom 20% of total water column depth.
